-- Top 3 Customer every quarterly   Order + customer + nation + region


-- REGION WISE 

explain using text 

SELECT  a.* ,D_C.CUST_NAME
FROM (
WITH DIM_ORDERS AS (

 SELECT * , 
 CASE WHEN month(ORDER_DATE) BETWEEN 1 AND 3 THEN   'Q1'
      WHEN month(ORDER_DATE) BETWEEN 4 AND 6 THEN   'Q2'
      WHEN month(ORDER_DATE) BETWEEN 7 AND 9 THEN   'Q3'
      WHEN month(ORDER_DATE) BETWEEN 10 AND 12 THEN 'Q4'

 END  WHICH_QUATER
 FROM MOCK_PROJECT_DB.CONSUMPTION.DIM_ORDERS
) 
SELECT Fct_order.CUST_ID , 
year(D_O.ORDER_DATE) AS YEAR ,
D_O.WHICH_QUATER,
SUM(Fct_order.ORDER_TOTALPRICE) AS TOTAL_ORDER_VALUE ,D_R.REGION_NAME,
dense_rank() OVER(PARTITION BY year(D_O.ORDER_DATE),D_O.WHICH_QUATER,D_R.REGION_NAME ORDER BY SUM(Fct_order.ORDER_TOTALPRICE) DESC ) AS RN 

FROM DIM_ORDERS D_O , MOCK_PROJECT_DB.CONSUMPTION.FACT_ORDER_CUSTOMER Fct_order , MOCK_PROJECT_DB.CONSUMPTION.DIM_REGION D_R
WHERE D_O.ORDER_ID = Fct_order.ORDER_ID and Fct_order.REGION_ID   = D_R.REGION_ID
group by Fct_order.CUST_ID,year(D_O.ORDER_DATE) , D_O.WHICH_QUATER ,D_R.REGION_NAME 

) a  , MOCK_PROJECT_DB.CONSUMPTION.DIM_CUSTOMER  D_C  
where a.CUST_ID = D_C.CUST_ID   and a.rn<=3
order by a.year , a.region_name 


--NATION WISE 
SELECT  a.* ,D_C.CUST_NAME
FROM (
WITH DIM_ORDERS AS (

 SELECT * , 
 CASE WHEN month(ORDER_DATE) BETWEEN 1 AND 3 THEN   'Q1'
      WHEN month(ORDER_DATE) BETWEEN 4 AND 6 THEN   'Q2'
      WHEN month(ORDER_DATE) BETWEEN 7 AND 9 THEN   'Q3'
      WHEN month(ORDER_DATE) BETWEEN 10 AND 12 THEN 'Q4'
      
 END  WHICH_QUATER
 FROM MOCK_PROJECT_DB.CONSUMPTION.DIM_ORDERS
) 
SELECT Fct_order.CUST_ID , 
year(D_O.ORDER_DATE) AS YEAR ,
D_O.WHICH_QUATER,
SUM(Fct_order.ORDER_TOTALPRICE) AS TOTAL_ORDER_VALUE ,D_R.NATION_NAME,
dense_rank() OVER(PARTITION BY year(D_O.ORDER_DATE),D_O.WHICH_QUATER,D_R.NATION_NAME ORDER BY SUM(Fct_order.ORDER_TOTALPRICE) DESC ) AS RN 

FROM DIM_ORDERS D_O , MOCK_PROJECT_DB.CONSUMPTION.FACT_ORDER_CUSTOMER Fct_order , MOCK_PROJECT_DB.CONSUMPTION.DIM_NATION D_R
WHERE D_O.ORDER_ID = Fct_order.ORDER_ID and Fct_order.NATION_ID   = D_R.NATION_ID
group by Fct_order.CUST_ID,year(D_O.ORDER_DATE) , D_O.WHICH_QUATER ,D_R.NATION_NAME 

) a  , MOCK_PROJECT_DB.CONSUMPTION.DIM_CUSTOMER  D_C  
where a.CUST_ID = D_C.CUST_ID   and a.rn<=3
order by a.year , a.nation_name 



































