  -- task 1
  
  CREATE or replace TASK MOCK_PROJECT_DB.RAW.ORDER_SUMMARY_DATE_UPDATE
  SCHEDULE = 'USING CRON 0 */24 * * 0-6 UTC'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  AS
  UPDATE ORDER_SUMMAR Y SET  order_date = TO_DATE(order_date, 'DD/MM/YYYY') WHERE order_date  REGEXP '../../....' ;


  -- alter task MOCK_PROJECT_DB.RAW.ORDER_SUMMARY_DATE_UPDATE resume;
  
  -- alter task MOCK_PROJECT_DB.RAW.ORDER_SUMMARY_DATE_UPDATE suspend;

  show tasks;
  select * from table(information_schema.task_history());



 select * from part_supply_supplier where suppkey=67014 and partkey=1467013


  -- task 2

  
  CREATE or replace TASK LINE_ITEM_SUPPLY_SHIPDATE_UPDATE
  SCHEDULE = 'USING CRON 0 */24 * * 0-6 UTC'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  AS
  UPDATE LINE_ITEM_SUPPLY SET  SHIPDATE = TO_DATE(SHIPDATE, 'DD/MM/YYYY') WHERE SHIPDATE  REGEXP '../../....' ;


  -- SELECT SHIPDATE FROM MOCK_PROJECT_DB.RAW.LINE_ITEM_SUPPLY
  -- WHERE SHIPDATE  REGEXP '../../....' ;


  -- alter task MOCK_PROJECT_DB.RAW.LINE_ITEM_SUPPLY_SHIPDATE_UPDATE resume;
  --  alter task MOCK_PROJECT_DB.RAW.LINE_ITEM_SUPPLY_SHIPDATE_UPDATE SUSPEND;
  -- SHOW TASKS




  

  -- TASK 3

  
  CREATE or replace TASK LINE_ITEM_SUPPLY_COMMITDATE_UPDATE
  SCHEDULE = 'USING CRON 0 */24 * * 0-6 UTC'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  AS
  UPDATE LINE_ITEM_SUPPLY SET  COMMITDATE = TO_DATE(COMMITDATE, 'DD/MM/YYYY') WHERE COMMITDATE  REGEXP '../../....' ;



  alter task MOCK_PROJECT_DB.RAW.LINE_ITEM_SUPPLY_COMMITDATE_UPDATE SUSPEND;

-- TASK 4


 CREATE or replace TASK LINE_ITEM_SUPPLY_RECEIPTDATE_UPDATE
  SCHEDULE = 'USING CRON 0 */24 * * 0-6 UTC'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  AS
  UPDATE LINE_ITEM_SUPPLY SET  RECEIPTDATE = TO_DATE(RECEIPTDATE, 'DD/MM/YYYY') WHERE RECEIPTDATE  REGEXP '../../....' ;


 alter task MOCK_PROJECT_DB.RAW.LINE_ITEM_SUPPLY_RECEIPTDATE_UPDATE SUSPEND;
 
  

 select * from  MOCK_PROJECT_DB.CONSUMPTION.SHIP_MODE_TRENDS_EVERY_YEAR_FOR_LAST_5_YEARS_REGION_WISE

